### ISSUE TITLE
OGWAPI unexpected behaviour

### ISSUE THREAD

**Issue by dimitris-karadimas** [vicinityh2020/issue-tracking#4]
Our Open Call demonstration app [vicinity-sammy-demo](https://github.com/vicinityh2020/vicinity-sammy-demo) uses Gateway API to receive things values. Things are queried when someone visits the [demo app](https://vicinity.optionsnet.gr/demo/) once per minute.
After some amount of time (not exactly identifiable how much time) the Gateway becomes unstable. Gateway version is 0.7.

Error is:
`	Jun 10, 2019 7:56:16 PM org.jivesoftware.smack.roster.Roster$5 processException
SEVERE: Exception reloading roster
org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). Waited for response using: IQReplyFilter: iqAndIdFilter (AndFilter: (OrFilter: (IQTypeFilter: type=error, IQTypeFilter: type=result), StanzaIdFilter: id=ZWpzV-61851)), : fromFilter (OrFilter: (FromMatchesFilter (full): null, FromMatchesFilter (ignoreResourcepart): 87793606-646c-4061-bb6c-d04f0cf9efac@vicinity.ws, FromMatchesFilter (full): vicinity.ws)).
        at org.jivesoftware.smack.SmackException$NoResponseException.newWith(SmackException.java:111)
        at org.jivesoftware.smack.AbstractXMPPConnection$8.run(AbstractXMPPConnection.java:1545)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

More details in the attached logs from gateway and agent, as well as gateway configuration.
[GatewayConfig.zip](https://github.com/vicinityh2020/issue-tracking/files/3273006/GatewayConfig.zip)
[gateway-logs.zip](https://github.com/vicinityh2020/issue-tracking/files/3273008/gateway-logs.zip)
[agent-logs.zip](https://github.com/vicinityh2020/issue-tracking/files/3273010/agent-logs.zip)

Any other information that may help is available.

**Comment by MooXo** [comment]
Please, update the latest version of the Gateway API.

**Comment by dimitris-karadimas** [comment]
Update in place, so far seems OK. Please allow us a few days to monitor for unexpected behavior.

**Comment by MooXo** [comment]
For inactivity i suggest this issue should be closed.
