### ISSUE TITLE
Vicinity agent authentication password

### ISSUE THREAD

**Issue by pesicsasa** [vicinityh2020/issue-tracking#5]
**Describe the bug**

Vicinity agent [v0.6.3.2](https://github.com/vicinityh2020/vicinity-agent/releases/download/v0.6.3.2/agent-build-0.6.3.2.zip) accepts 'test' password only, no matter what is set in vicinity.bavenir.eu webpage, Organisation Access Points tab. 

Additionally, if 'test' is set up as password in in agent configuration file (example-agent.json), no matter what password is set on vicinity.bavenir.eu webpage - Organisation Access Points tab, the agent will successfully authenticate itself. 

**To Reproduce**

1. Go to vicinity.bavenir.eu webpage, Organisation Access Points tab
2. Change password to anything but 'test', for example 'newpassword'
3. Change the password to 'newpassword' in agent configuration file (example-agent.json)
4. Try running agent.sh script on your machine
5. Look at logs, and search for error: 

`2019-07-03 11:30:33.832 1619 [main] ERROR s.i.v.a.clients.GatewayAPIClient -
org.restlet.resource.ResourceException: Unauthorized (401) - The request requires user authentication
        at org.restlet.resource.ClientResource.doError(ClientResource.java:592)
        at org.restlet.resource.ClientResource.handleInbound(ClientResource.java:1156)
        at org.restlet.resource.ClientResource.handle(ClientResource.java:1049)
        at org.restlet.resource.ClientResource.handle(ClientResource.java:1024)
        at org.restlet.resource.ClientResource.handle(ClientResource.java:929)
        at org.restlet.resource.ClientResource.get(ClientResource.java:639)
        at sk.intersoft.vicinity.agent.clients.GatewayAPIClient.get(GatewayAPIClient.java:145)
        at sk.intersoft.vicinity.agent.service.config.AgentConfig.updateLastConfiguration(AgentConfig.java:166)
        at sk.intersoft.vicinity.agent.service.config.AgentConfig.configureAgent(AgentConfig.java:282)
        at sk.intersoft.vicinity.agent.service.config.AgentConfig.configure(AgentConfig.java:127)
        at sk.intersoft.vicinity.agent.service.config.AgentConfig.configure(AgentConfig.java:151)
        at sk.intersoft.vicinity.agent.service.config.Configuration.configureAgents(Configuration.java:72)
        at sk.intersoft.vicinity.agent.service.StartStop.start(StartStop.java:37)
        at sk.intersoft.vicinity.agent.service.AgentServer.main(AgentServer.java:35)`

**Expected behavior**
The agent is supposed to successfully authenticate itself with the 'newpassword' changed on both ends (agent configuration file, vicinity.bavenir.eu webpage -Organisation Access Points tab).

**Comment by kostelni** [comment]
i'm not able to reproduce this issue. when i change agent credentials in agent config json, agent agent service uses any updates of config correctly in interaction with gateway.

to double check, reproduce issue and attach agent log (AGENT_FLD/logs/agent-yyyy-MM-dd.log)
interaction with GTW is fully logged, including credentials, that agent realy uses

**Comment by pesicsasa** [comment]
The issue was consistent during our tests, however, at this point we are not able to reproduce.
